"""Generate the rulebook table in docs/DESIGN-BRAIN.md section 7 from the registry.

The doc has claimed "GENERATED from the registry - do not hand-edit" since v2,
but the snippet it pointed at was a placeholder, so the table was in fact
hand-maintained and had drifted: four rules that can emit a severity other
than their default were all printed as plain `warn`, and `ok` is error-driven,
so the two that escalate to `error` understated exactly the case a reader most
needs to know about.

    python tools/gen_rule_table.py            # print the table
    python tools/gen_rule_table.py --write    # splice it into the doc
    python tools/gen_rule_table.py --check    # exit 1 if the doc is stale

`tests/test_docs.py` runs the --check path, so the claim is now true.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from chartwright.design.model import RULES  # noqa: E402
import chartwright.design.rules  # noqa: E402,F401  (import for rule registration)

DOC = REPO / "docs" / "DESIGN-BRAIN.md"
BEGIN = "<!-- BEGIN rule-table: generated by tools/gen_rule_table.py; do not hand-edit -->"
END = "<!-- END rule-table -->"


def render() -> str:
    lines = ["| id | sev | fix | data | since | rule |", "|---|---|---|---|---|---|"]
    for rid in sorted(RULES):
        r = RULES[rid]
        # ASCII hyphen for "no", not an em dash: the glyph carries no meaning
        # here, and 49 rows of it swamped the file's real punctuation.
        lines.append(
            f"| `{r.id}` | {r.severity_label} | {'✔' if r.fixable else '-'} | "
            f"{'⚡' if r.data_aware else '-'} | {r.since} | {r.doc} |"
        )
    return "\n".join(lines)


def splice(text: str, table: str) -> str:
    block = f"{BEGIN}\n\n{table}\n\n{END}"
    if BEGIN in text and END in text:
        return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block,
                      text, flags=re.S)
    raise SystemExit(f"markers not found in {DOC}; add {BEGIN} / {END} around the table")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="splice the table into the doc")
    ap.add_argument("--check", action="store_true", help="exit 1 if the doc is stale")
    args = ap.parse_args(argv)

    table = render()
    if not (args.write or args.check):
        print(table)
        return 0
    text = DOC.read_text(encoding="utf-8")
    new = splice(text, table)
    if args.check:
        if new != text:
            print("docs/DESIGN-BRAIN.md rule table is STALE; run: "
                  "python tools/gen_rule_table.py --write")
            return 1
        print(f"rule table up to date ({len(RULES)} rules)")
        return 0
    DOC.write_text(new, encoding="utf-8")
    print(f"wrote {len(RULES)} rules into {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
